# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install xfce4 -y
    sudo snap install pycharm-community --classic
    curl -sSL https://get.docker.com | sh
    sudo usermod -aG docker vagrant
  SHELL
end
